apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: container1
  name: container1
spec:
  containers:
  - image: nginx
    name: container1
  - image: busybox
    name: container2
    command: ["/bin/sh", "-c", sleep 4800"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
