apiVersion: v1
kind: PersistentVolume
metadata:
  name: msp-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /temp/servicedata
  persistentVolumeReclaimPolicy: Retain
